In [3]:
import pandas as pd

database = pd.read_csv("China_Exports.csv", sep=';')

#Stripping leading and trailing whitespace and control characters from column names and text fields
database.columns = database.columns.str.strip()
database[["Country", "City","SH4 Description"]] = database[["Country", "City","SH4 Description"]].apply(lambda x: x.str.strip())
#Extracting the month name by splitting the string on the period, selecting the second element, and stripping whitespace
database["Month"] = database["Month"].str.split(".").str[1].str.strip()

display(database.head(10))

,Year,Month,Country,City,SH4 Code,SH4 Description,US$ FOB,Net Weight
0,2025,January,China,Rio de Janeiro - RJ,2709,Crude oil from petroleum and bituminous minerals,1313923067,2584337261
1,2025,January,China,Canaã dos Carajás - PA,2601,"Iron ores and concentrates, including roasted ...",339611216,4754695874
2,2025,January,China,Parauapebas - PA,2601,"Iron ores and concentrates, including roasted ...",335845341,4707618276
3,2025,January,China,Itaguaí - RJ,2601,"Iron ores and concentrates, including roasted ...",326936425,5467046000
4,2025,January,China,Venâncio Aires - RS,2401,Unmanufactured tobacco; tobacco refuse,217180226,21562200
5,2025,January,China,Ilhabela - SP,2709,Crude oil from petroleum and bituminous minerals,198176136,398797422
6,2025,January,China,Ribas do Rio Pardo - MS,4703,"Chemical wood pulp, soda or sulphate, other th...",164472247,306600000
7,2025,January,China,Nova Lima - MG,2601,"Iron ores and concentrates, including roasted ...",101105088,1406787044
8,2025,January,China,São Gonçalo do Rio Abaixo - MG,2601,"Iron ores and concentrates, including roasted ...",94464113,1311456029
9,2025,January,China,Lençóis Paulista - SP,4703,"Chemical wood pulp, soda or sulphate, other th...",90525040,257652000

In [5]:
database.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25943 entries, 0 to 25942
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             25943 non-null  int64
 1   Month            25943 non-null  object
 2   Country          25943 non-null  object
 3   City             25943 non-null  object
 4   SH4 Code         25943 non-null  int64
 5   SH4 Description  25943 non-null  object
 6   US$ FOB          25943 non-null  int64
 7   Net Weight       25943 non-null  int64
dtypes: int64(4), object(4)
memory usage: 1.6+ MB

In [7]:
#Analysing each month value and formating it
export_amount_months = database[["Month","US$ FOB"]].groupby("Month").sum(numeric_only=True)

def format(value):
    format_value = f"US$ {value:,}"
    return format_value

export_amount_months["US$ FOB"] = export_amount_months["US$ FOB"].apply(format)


display(export_amount_months)

                     US$ FOB
Month
April      US$ 8,762,770,272
August     US$ 9,360,816,092
December   US$ 7,125,729,427
February   US$ 5,205,994,816
January    US$ 5,514,754,225
July       US$ 9,824,343,120
June       US$ 9,877,481,910
March      US$ 8,903,666,279
May        US$ 9,590,510,024
November   US$ 8,163,292,700
October    US$ 9,067,853,985
September  US$ 8,543,031,860

In [9]:
#Most exported products troughout the months

export_amount_months = database[["SH4 Description","US$ FOB"]].groupby("SH4 Description").sum()
export_amount_months = export_amount_months.sort_values(by="US$ FOB", ascending=False)

export_amount_months["US$ FOB"] = export_amount_months["US$ FOB"].apply(format)
display(export_amount_months.head(6))

                                                               US$ FOB
SH4 Description
Soya beans, whether or not broken                   US$ 34,505,104,723
Crude oil from petroleum and bituminous minerals    US$ 20,045,592,344
Iron ores and concentrates, including roasted i...  US$ 19,581,100,549
Meat of bovine animals, frozen                       US$ 8,842,569,470
Chemical wood pulp, soda or sulphate, other tha...   US$ 4,129,752,323
Cane or beet sugar and chemically pure sucrose,...   US$ 1,899,448,721

In [63]:
#The city with more exports to China in March

table_march = database.loc[database["Month"]=="March",:]
table_march = table_march[["City","SH4 Description","US$ FOB"]].groupby("City").sum()
table_march = table_march.sort_values(by="US$ FOB",ascending=False)
table_march["US$ FOB"] = table_march["US$ FOB"].apply(format)
table_march = table_march.reset_index()

display(table_march)

,City,SH4 Description,US$ FOB
0,Rio de Janeiro - RJ,Crude oil from petroleum and bituminous minera...,"US$ 1,080,855,777"
1,Paranaguá - PR,"Soya beans, whether or not brokenMeat and edib...","US$ 531,563,278"
2,Canaã dos Carajás - PA,"Iron ores and concentrates, including roasted ...","US$ 330,649,207"
3,Rio Verde - GO,"Soya beans, whether or not brokenSoya-bean oil...","US$ 317,560,044"
4,Parauapebas - PA,"Iron ores and concentrates, including roasted ...","US$ 232,121,393"
...,...,...,...
624,Cabedelo - PB,"Quartz (other than natural sands); quartzite, ...",US$ 6
625,Juatuba - MG,Accessories for tubes of aluminum,US$ 5
626,Iporã - PR,"Flours, meals and pellets, of meat or meat off...",US$ 3
627,Dois Irmãos - RS,"Packing cases, boxes, crates, drums and simila...",US$ 1
628,Sarzedo - MG,"Iron ores and concentrates, including roasted ...",US$ 0

In [61]:
print(table_march.columns)

Index(['SH4 Description', 'US$ FOB'], dtype='object')

In [ ]:
#Automating tha analysis by city



city = table_march.loc[0, "City"]   

table_city = database.loc[(database["Month"]=="March") & (database["City"]==city), :]

table_products_city = table_city[["SH4 Description","US$ FOB"]].groupby("SH4 Description").sum()
table_products_city = table_products_city.sort_values(by="US$ FOB",ascending=False)

table_products_city["US$ FOB"] = table_products_city["US$ FOB"].apply(format)

print(f"The most exported product by {city}:")
display(table_products_city)

The most exported product by Rio de Janeiro - RJ:

                                                              US$ FOB
SH4 Description
Crude oil from petroleum and bituminous minerals    US$ 1,079,651,397
Copper waste and scrap                                    US$ 602,684
New pneumatic tyres, of rubber                            US$ 323,728
Precious stones (other than diamonds) and semi-...         US$ 70,691
Prefabricated buildings                                    US$ 51,316
Parts suitable for use solely or principally wi...         US$ 41,767
Granite, porphyry, basalt, sandstone and other ...         US$ 24,700
Other articles of iron or steel                            US$ 23,554
Other tubes, pipes and hollow profiles (for exa...         US$ 21,887
Automatic data-processing machines and units th...         US$ 16,389
Live fish                                                  US$ 13,016
Articles of jewellery and parts thereof, of pre...          US$ 3,848
Insulated (including enamelled or anodised) wir...          US$ 3,092
Electrical machines and apparatus, having indiv...          US$ 2,833
Articles for the conveyance or packing of goods...          US$ 2,545
Other articles of plastics and articles of othe...          US$ 1,366
Mixtures of odoriferous substances and mixtures...            US$ 479
Cartons, boxes, cases, bags and other packing c...            US$ 454
Printed books, brochures, leaflets and similar ...             US$ 14
Stoppers, caps and lids (including crown corks,...             US$ 10
Perfumes and toilet waters                                      US$ 3
Women's or girls' suits, ensembles, jackets, bl...              US$ 2
Woven fabrics of artificial staple fibres                       US$ 2
Pencils (other than pencils of heading 9608), c...              US$ 0
Men's or boys' suits, ensembles, jackets, blaze...              US$ 0